name: actions_onmain
run-name: Continue implement
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "mvn --batch-mode --update-snapshots build"
  
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - run: echo "mvn --batch-mode --update-snapshots test"