name: github-actions
run-name: Continue implement
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build with maven
      - uses: actions/checkout@v3
      - run: echo "mvn --batch-mode --update-snapshots build"
  
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: test
      - uses: actions/checkout@v3
      - run: echo "mvn --batch-mode --update-snapshots test"
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: build with maven
      - uses: actions/checkout@v3
      - run: echo "Deploy"